### ISSUE TITLE
Relative Path Images Not Displaying

### ISSUE THREAD

**Issue by hmelendez001** [chadbaldwin/simple-blog-bootstrap#2]
I noticed that when I include an &lt;img&gt; image with a full path the image displays fine.  As in this example:

&lt;img src="https://i2.wp.com/indianaiproduction.com/wp-content/uploads/2019/09/24-seaborn-heatmap-correlation.png?resize=768%2C473&ssl=1"&gt;

<img src="https://i2.wp.com/indianaiproduction.com/wp-content/uploads/2019/09/24-seaborn-heatmap-correlation.png?resize=768%2C473&ssl=1">
Source: https://indianaiproduction.com/seaborn-heatmap/

But when I do it as a relative image path (for example: &lt;img src="images/myimage.png"&gt;) it shows up fine on the GitHub "Preview" tab but once it's deployed the image does not show up. I don't know if this is a general GitHub issue with relative paths or if it's specific to this project. Any pointers on correcting this?

**Comment by akashicMarga** [comment]
@chadbaldwin i am trying to attach images in my blog post preview works but after hosting image is not loading. i tried all the changes suggested above. it would be great if you could help me out.

https://github.com/akashicMarga/akashicMarga.github.io/blob/main/_posts/2024-10-03-Introduction-to-AI-Compilers-and-Kernel-Design-2.md

**Comment by hsun-code** [comment]
@akashicMarga As I tried in https://github.com/hsun-code/hsun-code.github.io/blob/main/_posts/2025-03-07-check-cpu-usage-with-sar.md, it works for me by using `![image-name](/images/xx.png)` as suggested above.

Note that `![image-name](/_images/xx.png)` does't work, where I put my image under `_images`, with an extra prefix `_`. I'm not an expert in js or html. Regarding your case,  I suppose it might be an issue for you to put images under `_posts`, that is, with a leading `_`. The encoded URL might be different as I guess.
